### ISSUE TITLE
Ability to set scale on UI to start at 0

### ISSUE THREAD

**Issue by ctk21** [ocurrent/current-bench#103]
Is it possible to change the way the raw results are plotted such that they always include 0 on the y-axis (that is `[0, y_max+delta]`)? _(see screenshot at end)_

Right now you have them plotted as `[y_min-delta, y_max+delta]` for each run which makes the graphs not easy to interpret across a large number of benchmarks, the reader has to inspect the axis scale because the shape might not be significant. For example the first time_secs plot has a range of `[101.9, 102.1]` that is `102 +/- 0.1%` but visually the changes looks proportionally more significant because of the zoomed y-axis. Also when comparing graphs, we could have a graph with range `[91, 101]` that could have the same visual shape as  `[101.9, 102.1]` but the two could have very different implications.

I’m open to other scaling proposals that also keep things easy to compare: e.g. display as normalised deviation from median/mean with all axes for the plots on a common y-scale. However these other scaling proposals might not be as easy to implement as just making `0` the minimum for all our positive valued metrics. 

@shakthimaan requested I file the issue here

![Current-bench-Sandmark-2-April-20-2021](https://user-images.githubusercontent.com/1682628/115532906-22553f80-a28e-11eb-89cd-ac58df47d497.png)

**Comment by gs0510** [comment]
@ctk21 This is definitely doable, I'll implement this and gather some feedback from everyone to see what they think.

**Comment by rizo** [comment]
This is addressed in #74 where I included some example graphs. Naturally the result makes the graphs much smoother. I agree we should get some feedback on this before using this.

**Comment by gs0510** [comment]
Fixed by #74 :)
