### ISSUE TITLE
Ability to start and run only PostgreSQL and frontend

### ISSUE THREAD

**Issue by shakthimaan** [ocurrent/current-bench#107]
For Multicore OCaml, we provision our hardware with specific configuration, and will re-run the experiments with different settings for compiler analysis. For such cases, we would like to use an ETL tool to just load the benchmark results and use the PostgreSQL and frontend Docker containers only for visualization.

**Comment by gs0510** [comment]
This can be done! If you remove [the pipeline docker image](https://github.com/ocurrent/current-bench/blob/main/environments/production.docker-compose.yaml#L46) you'll have a postgres database and a frontend running. As long as the tool is able to add the data to the database in the json format, there shouldn't be a problem.

**Comment by punchagan** [comment]
This can be done by running the following command, from the root of the repository, after configuring the `development.env` file correctly.  

```sh
./scripts/dc.sh up --build frontend db graphql-engine db-migrate
```
This runs the development configuration, but you could run a similar command if you wish to run the production configuration.

**Comment by gs0510** [comment]
@punchagan Can you add this to `HACKING.md`? :) Thanks! We can close this issue once we do that :))
