### ISSUE TITLE
Support for native builds for bare metals instead of Docker container

### ISSUE THREAD

**Issue by shakthimaan** [ocurrent/current-bench#108]
For Multicore OCaml, we would like to be able to build and run benchmarks on bare metal machines. It will be good to create an OCurrent pipeline just for native builds, while, still using the PostgreSQL database and frontend containers.

**Comment by gs0510** [comment]
Do you want this pipeline to be triggered on PRs or to run it on a branch or both? 

I'll try to prototype this to see what it would look like in the current pipeline, but we wouldn't want repositories who enroll in current-bench to run their benchmarks outside of docker.

**Comment by shakthimaan** [comment]
> Do you want this pipeline to be triggered on PRs or to run it on a branch or both?

Both.

> but we wouldn't want repositories who enroll in current-bench to run their benchmarks outside of docker.

The requirement here is to run on bare metal and not in Docker, as we don't want the overhead of the Docker layer.

**Comment by shakthimaan** [comment]
With hyperthreading disabled, the Docker results are close to bare metal as observed in https://github.com/ocurrent/current-bench/issues/151. Hence, this is not a requirement anymore.
