### ISSUE TITLE
Commit numbers are duplicated on the X axis

### ISSUE THREAD

**Issue by emillon** [ocurrent/current-bench#124]
Hi!

When there is little data, there's some "interpolation" happening and the same commit gets printed several times on the X axis:

![image](https://user-images.githubusercontent.com/496345/118637200-d25a9180-b7d5-11eb-909e-5bf6ecc14010.png)

In case the different points corresponds to various days, it might work better to display dates here, or just each commit once maybe.

**Comment by gs0510** [comment]
We have an open issue #39 to look into this, some of the commits are repeated because the docker image in the pipeline is fetched everyday so the benchmarks run again, but surely they aren't these many!

**Comment by gs0510** [comment]
The entries are cached by ocurrent, and because ocurrent runs the same build-job/run-job again and the side effect is writing to the database. We don't write to the database anymore if ocurrent runs the same run-job and has the same commit anymore, so this doesn't happen anymore. (#162)
