### ISSUE TITLE
Formatting of floating point numbers

### ISSUE THREAD

**Issue by emillon** [ocurrent/current-bench#125]
Hi,

By default current-bench renders floats in scientific notation in several places:

![image](https://user-images.githubusercontent.com/496345/118637679-5dd42280-b7d6-11eb-88a1-033ae157b511.png)

In that particular case, this is to track a file size, so something like 13.09MB is preferable to 1.309e+7 (13.09M or 13.09e+6 could work too).

**Comment by shubhamkumar13** [comment]
@gs0510 we can close this issue? since #206 is merged

**Comment by gs0510** [comment]
As @punchagan pointed out, we can close it once we handle the edge cases as well :)
