### ISSUE TITLE
Broken link to current logs

### ISSUE THREAD

**Issue by rizo** [ocurrent/current-bench#127]
The links to the log pages are currently broken.

<img width="798" alt="Screenshot 2021-05-18 at 12 35 47" src="https://user-images.githubusercontent.com/308413/118644297-945d6d80-b7d5-11eb-9f8d-20222f959416.png">

**Comment by gs0510** [comment]
Is this for all logs? Or it is the logs that were accidentally deleted?

**Comment by gs0510** [comment]
It's happening because the env variable is wrong here: https://github.com/ocurrent/current-bench/blob/main/frontend/src/CommitInfo.res#L43. Fixing and redeploying.

**Comment by rizo** [comment]
I think we should have some kind of validation for this. Let's keep this issue for now.
