### ISSUE TITLE
Capture failed state in UI

### ISSUE THREAD

**Issue by emillon** [ocurrent/current-bench#129]
Hi,

Some kind of errors are not captured in the UI. For example when docker fails to run, the error is only displayed on the checks div:

![image](https://user-images.githubusercontent.com/496345/118649040-58310980-b7e3-11eb-931d-076a0c9115a1.png)

But clicking "details" navigates to a failure state with no information:

![image](https://user-images.githubusercontent.com/496345/118649125-6f6ff700-b7e3-11eb-8b74-b34f52f526d4.png)

I would expect some information about what happened, maybe including the command or some logs if it's relevant:

![image](https://user-images.githubusercontent.com/496345/118649418-c5dd3580-b7e3-11eb-8561-f5a118b32def.png)

**Comment by gs0510** [comment]
You can see why the PR failed in the logs linked on top of the graphs, but it's not intuitive. I think even highlighting the logs link when the benchmarks fail should work.

**Comment by rizo** [comment]
This should be fixed when https://github.com/ocurrent/current-bench/pull/120 is completed.

**Comment by punchagan** [comment]
Closed in #207
