### ISSUE TITLE
`Main` doesn't take back to main view

### ISSUE THREAD

**Issue by gs0510** [ocurrent/current-bench#136]
On the UI, clicking on `Main` doesn't take the user back to the graphs of the `main` branch.

**Comment by tatchi** [comment]
Happy to look at the one :) Can you assign me the issue @gs0510 ?

**Comment by gs0510** [comment]
Yes ofc! Thanks @tatchi!

**Comment by tatchi** [comment]
I gave it a closer look and realized that the `Main` link in the sidebar has nothing to do with the branch/PR. It refers to the `Main` benchmark (the default one). This feature was implemented in https://github.com/ocurrent/current-bench/pull/69

When the repo has no benchmarks configured (benchmark_name column is `NULL`), a default `Main` one is displayed. You can see a video below with a repo that has two benchmarks:

https://user-images.githubusercontent.com/5595092/120752620-47ce9d80-c50a-11eb-9be8-744168db5a47.mov

Should you want to see the master data, you can click on the `master` link in the breadcrumb (as shown at the end of the video)

**Comment by gs0510** [comment]
Ah! I guess it will make sense when we have multiple benchmarks, but right now it makes you think it's the main branch. Can we do something to make it more intuitive?
