### ISSUE TITLE
Long opam installs could be cached

### ISSUE THREAD

**Issue by Ngoguey42** [ocurrent/current-bench#140]
While Irmin's benchmarks take ~4 minutes, the opam env building takes ~13 minutes.

I'm no expect but I suppose that the caching of docker builds could be tweaked to speed this up.

**Comment by gs0510** [comment]
AFAIK the problem is that if the docker that builds up the env is cached, there's no guarantee that things won't be cached for the benchmarks container as well. I will look more into this!

**Comment by punchagan** [comment]
This should be fixed with #167.
