### ISSUE TITLE
Unexpectedly slow benchmark run

### ISSUE THREAD

**Issue by Ngoguey42** [ocurrent/current-bench#141]
I noticed huge variances on the runtime of https://github.com/mirage/irmin/pull/1441

wall/cpu time of some runs of the tree.exe benchmark (these timings are recorded from within tree.exe (the benchmark program)):
- 25min13s/2min10s: http://autumn.ocamllabs.io:8081/job/2021-06-03/225705-docker-pread-718e47
- 1min18s/1min18s: http://147.75.32.19:8081/job/2021-06-03/171324-docker-pread-03e054
- 1min45s/1min45s: http://autumn.ocamllabs.io:8081/job/2021-06-07/092436-docker-pread-fc045d
- 3min13s/1min53s: http://autumn.ocamllabs.io:8081/job/2021-06-07/094240-docker-pread-cb153b

About that last one I noticed that https://github.com/ocaml/dune/pull/4678 ran at the same time. It would explain that wall/cpu time difference.

Timeline of events:
1. `2021-06-07 09:29.36`: 1441-build started first
2. `2021-06-07 09:38.46`: 4678-build arrived and got stuck on `Waiting for resource in pool docker`
3. `2021-06-07 09:42.40`: 1441-build finished and both 1441-run and 4678-build started at the same time
4. `2021-06-07 09:44.03`: 4678-build finished and 4678-run started while 1441-run was still running

URLs:
- 1441-build: http://autumn.ocamllabs.io:8081/job/2021-06-07/092936-docker-build-6f0b9b
- 1441-run: http://autumn.ocamllabs.io:8081/job/2021-06-07/094240-docker-pread-cb153b
- 4678-build: http://autumn.ocamllabs.io:8081/job/2021-06-07/093846-docker-build-09c515
- 4678-run: http://autumn.ocamllabs.io:8081/job/2021-06-07/094403-docker-pread-4a4bda

**Comment by gs0510** [comment]
Thanks for the detailed log @Ngoguey42! Will look into this!

**Comment by Ngoguey42** [comment]
https://github.com/ocurrent/current-bench/blob/main/pipeline/lib/pipeline.ml#L104-L109

Could this be because the `pool` is not passed to `pread_log` here? (got the insight from @TheLortex)

**Comment by gs0510** [comment]
Aah good catch! But this would mean that the interleaving you mention in the last scenario will be taken care of. Doesn't explain `25min13s/2min10s: http://autumn.ocamllabs.io:8081/job/2021-06-03/225705-docker-pread-718e47` right?

**Comment by Ngoguey42** [comment]
Yes. I don't know about that one

**Comment by gs0510** [comment]
With pool fixed and cached opam installs, this is faster now. :) Please re-open if you see this issue again! Thanks!
