### ISSUE TITLE
Ensure the opam repository is up to date before building the project

### ISSUE THREAD

**Issue by rizo** [ocurrent/current-bench#15]
The docker image produced by current-bench to run the benchmarks might not be using an up to date opam repository.

This can be causing errors during package installation and terminating the benchmark execution with "Docker build exited with status 20".

@samoht
> I think the base ocaml-ci images are tracking opam-repository and trigger a rebuild whenever a new version of a dependency is merged in opam-repository. Would be nice if ocaml-bench could do something similar?

**Comment by avsm** [comment]
You can actually manually override that 'schedule:weekly' by clicking on the `pull` box from the UI and clicking rebuild. It's not ideal, but a useful workaround for when there are decoupled components. (e.g. we do this in opam-repo-ci when we push new trunk images of the compiler and want something tested)

**Comment by rizo** [comment]
Thanks for the tip, @avsm! Unfortunately it seems like the base image is out of date in this case, so `pull` didn't help.

**Comment by rizo** [comment]
It seems that we were using an incorrect base image (`ocurrent/opam` instead of `ocaml/opam`). But even in that case, the images are only rebuilt weekly as suggested by https://github.com/ocurrent/docker-base-images/blob/25f48d7ca661bc43ef53e8dc2b396fcc30928855/src/pipeline.ml#L8.

**Comment by gs0510** [comment]
This is fixed by #55
