### ISSUE TITLE
Don't rerun the benchmark if the PR is old

### ISSUE THREAD

**Issue by gs0510** [ocurrent/current-bench#204]
When we redeploy current-bench, we currently rerun for all the PRs that we don't have any data for. This means that we might run on very very old PRs that nobody is really looking at. I'm not sure if there's a way to get this information from ocurrent, but we should be able to look at the commit date and if it's older than let's say a month, we don't run the benchmarks. The benchmarks will still run if someone actually pushes to the PR (since the head commit won't be old anymore).

**Comment by punchagan** [comment]
On a similar note, we could also avoid running benchmarks on Draft PRs? If it seems like a useful idea, we could create a new issue for this.

**Comment by gs0510** [comment]
I think sometimes folks might still want to run it on draft PRs? I'm not sure of we want to avoid running on draft PRs :) This is just a feeling though, not based on any actual evidence....

**Comment by punchagan** [comment]
Closed in #211
