### ISSUE TITLE
Auto-cancelled jobs are incorrectly shown as "Running" in the UI

### ISSUE THREAD

**Issue by punchagan** [ocurrent/current-bench#212]
Examples: 
http://autumn.ocamllabs.io/ocaml/dune/pull/5191
http://autumn.ocamllabs.io/ocaml/dune/pull/5181

**Comment by punchagan** [comment]
This could just be a problem with the migrated DB, since we don't update the `failed` column when migrating data from the `benchmarks` table to the `benchmark_metadata` table.

**Comment by gs0510** [comment]
The job was auto-cancelled because the PR was merged. And it was merged after I ran the integration, so we need to handle the case where we get a cancellation and mark it failed (or add a cancelled stage?).

**Comment by gs0510** [comment]
Fixed by #231
