### ISSUE TITLE
Status not handled correctly

### ISSUE THREAD

**Issue by gs0510** [ocurrent/current-bench#237]
For http://autumn.ocamllabs.io/mirage/irmin/pull/1653, we run the benchmarks succesfully and display them but we still get a "failed" on the status on the UI.
![Screenshot from 2021-12-06 19-28-45](https://user-images.githubusercontent.com/8718814/144901745-c4cf224b-6a23-4e2b-a538-211e3b8aa029.png)

FWIW the benchmarks did fail before, so I think we just forget to set the failed status to false when they eventually run successfully.

**Comment by punchagan** [comment]
Thanks for the catch, @gs0510. I've updated the DB to fix the UI for this specific PR and sent a PR to fix the bug.
