### ISSUE TITLE
Graph overlays

### ISSUE THREAD

**Issue by art-w** [ocurrent/current-bench#246]
The plotting library dygraph used on the frontend supports multi-line graph (see an [example](https://dygraphs.com/gallery/#g/temperature-sf-ny)). It would nice to collapse related metrics in one plot. For example, the `-dtimings` used to benchmark the ocaml compiler produces a lot of information, but we only keep the total / first line right now:

```
0.398s src/stage1/grammarFunctor.ml
  0.012s parsing
    0.012s parser
  0.120s typing
  0.009s transl
  0.257s generate
    ...
```

The json will need to be upgraded so that the client can specify the related metrics that should be displayed in one multi-line graph. There are a couple of solutions with different tradeoffs:

- Add more nesting? (requires a schema change, but guarantees that units are the same)

```json
   "metrics": [
	{
	  "name": "time",
	  "units": "secs",
	  "value": {"parsing":0.012, "typing":0.120, "generate":0.257}
	},
```

- Use the metric name as an indication of hierarchy? (= no change to the schema, just frontend work)

```json
{ "version": 2,
  "results": [
    {
      "name": "dtimings",
      "metrics": [
	{
	  "name": "grammarFunctor/parsing",
	  "units": "secs",
	  "value": 0.012
	},
	{
	  "name": "grammarFunctor/typing",
	  "units": "secs",
	  "value": 0.120
	},
	{
	  "name": "grammarFunctor/generate",
	  "units": "secs",
	  "value": 0.257
	},
```

- Or use the configuration to specify multiline graphs separately? (could be done as a second step to the previous option, to remove the analysis of paths in metrics names)

```json
{ "config": {
       "plots": [
            {
             "name": "example",
             "kind": "stack",
             "data": [ "grammarFunctor.parsing", "grammarFunctor.typing" ]
            }
       ]
   },
 "metrics": [
	{
	  "name": "grammarFunctor.parsing",
	  "units": "secs",
	  "value": 0.012
	},
	{
	  "name": "grammarFunctor.typing",
```

While the first option is less verbose, I'm bias to option 2 as it is much simpler to get up and running. We could then improve in either direction.

**Comment by gs0510** [comment]
I like both ideas 2 and 3, but I agree that 2 is easier to get started with! cc @shubhamkumar13  :)

**Comment by shubhamkumar13** [comment]
I agree with @art-w and @gs0510 the second option doesn't interfere with the schema and is easier to test
