### ISSUE TITLE
HTTP api for submitting results

### ISSUE THREAD

**Issue by art-w** [ocurrent/current-bench#280]
Current-Bench provides two nice features that are currently bundled together:
1. Evaluating the benchmarks in a stable environment
2. Reading the results with pretty graphs on the web UI

Some clients are not able to fit in the first step because they have to run on their own hardware. They would however benefit from the web interface, so we could let them submit their benchmarks results via a rest API to skip step 1. The API would mostly require:
- a secret token for validation
- the author/repo
- the commit hash (and date?)
- the "main" branch or a PR id/name
- and the json metrics in the same format as we normally expect

**Comment by gs0510** [comment]
Yes, this is a great idea! One of the ideas separating the UI and the pipeline but one of the concerns was that the user would write to a different DB and then they'd need to have a different URL as well, but the API solves that very nicely!

**Comment by punchagan** [comment]
Closed in #287
