### ISSUE TITLE
Undesirable redirect to the main branch result when checking a PR

### ISSUE THREAD

**Issue by gpetiot** [ocurrent/current-bench#285]
Thank you for the work on current-bench! Here is a small quirk I noticed and I didn't see any report about it.

For one of my PR, here is the link I get to check the benchmarks:
https://autumn.ocamllabs.io/ocaml-ppx/ocamlformat/pull/1609

But clicking on this link redirects to (the main branch):
https://autumn.ocamllabs.io/ocaml-ppx/ocamlformat?worker=autumn&image=ocaml/opam:debian-11-ocaml-4.13

And to go on the results for the relevant PR I have to scroll down the list on the left and click on:
https://autumn.ocamllabs.io/ocaml-ppx/ocamlformat/pull/1609?worker=autumn&image=ocaml/opam:debian-11-ocaml-4.13

Would it be possible to directly go to that page instead?

(As a bonus I would love to have the log to check whether the -99% is due to a failure of ocamlformat or not but I'm sure people already asked for this)

**Comment by gs0510** [comment]
Ah, yes this is not intended!! Thanks for the report @gpetiot!

Also, we have a partial log here: http://autumn.ocamllabs.io:8081/job/2022-01-28/110849-ocluster-build-87cd3f
Does that help at all? We used to have a more comprehensive log, I think we can try to enable that again. Thanks again!

**Comment by gpetiot** [comment]
> Also, we have a partial log here: http://autumn.ocamllabs.io:8081/job/2022-01-28/110849-ocluster-build-87cd3f Does that help at all? We used to have a more comprehensive log, I think we can try to enable that again. Thanks again!

Thanks I didn't notice this link, I think it could be made more noticeable (e.g. using the same style blue+underline for the link, and personally I think that the name of the build "110849-ocluster-build-87cd3f" only adds some "noise" and is not very useful for the end user, the link could just be named "execution logs").

This log is a bit rough indeed, if there was a more comprehensive log it wouldn't be a bad thing I think, if that doesn't involve too much work for the maintainers of course.

Would it be possible to add an _optional_ field in the JSON object that current-bench expects, e.g. each result item would have the fields `{name; metrics; output}` (or `log`), the contents of this last field would just be printed verbatim in the log.

**Comment by gs0510** [comment]
The redirection is fixed by #289 (so it works now :))

>Thanks I didn't notice this link, I think it could be made more noticeable (e.g. using the same style blue+underline for the link, and personally I think that the name of the build "110849-ocluster-build-87cd3f" only adds some "noise" and is not very useful for the end user, the link could just be named "execution logs").

Ah yes, a nice idea! I'll open a new issue re. this.

> Would it be possible to add an optional field in the JSON object that current-bench expects, e.g. each result item would have the fields {name; metrics; output} (or log), the contents of this last field would just be printed verbatim in the log.

yes this also should be doable! :) Will open another issue re this.

Thanks for all the feedback, we really appreciate it! :)

**Comment by art-w** [comment]
> This log is a bit rough indeed, if there was a more comprehensive log it wouldn't be a bad thing I think, if that doesn't involve too much work for the maintainers of course.

For a long time we did not support debug logs so that's probably why ocamlformat `make bench` output is so concise... It's now possible to print all the debug information that you need during the execution of `make bench` (as long as your debug messages doesn't look like json!) This is intended for in depth debugging as you still have to check the logs for investigation.

Regarding adding an `output` or `log` field in the json, the individual metrics support a `"description"` field that might be useful if you wanted to associate a **short** message to explain the results. The description will show up in the UI near its graph so it's a lot more visible than the output logs (but it also has a lot less room!)

Currently the json produced by ocamlformat looks like:

```json
{
  "results": [
    {
      "name": "ocamlformat numeric:conventional (source.ml)",
      "metrics": {
        "monotonic-clock": 42268412,
        "minor-allocated": 5240680.666666666,
        "major-allocated": 495869.23333333334
      }
    },
    ...
  ]
}
```

The extended new format of the json can look like:

```json
{
  "results": [
    {
      "name": "ocamlformat numeric:conventional (source.ml)",
      "metrics": [
        {
          "name": "monotonic-clock",
          "value": 42268412,
          "units": "s",
          "trend": "lower-is-better",
          "description": "A Short Message!"
        },
        ...
      ]
    },
    ...
  ]
}
```

(The fields `units`, `trend` and `description` are optional)

@gpetiot > Does either of this helps? :)

**Comment by gpetiot** [comment]
> For a long time we did not support debug logs so that's probably why ocamlformat `make bench` output is so concise... It's now possible to print all the debug information that you need during the execution of `make bench` (as long as your debug messages doesn't look like json!) This is intended for in depth debugging as you still have to check the logs for investigation.


> Regarding adding an `output` or `log` field in the json, the individual metrics support a `"description"` field that might be useful if you wanted to associate a **short** message to explain the results. The description will show up in the UI near its graph so it's a lot more visible than the output logs (but it also has a lot less room!)


Great, I will give a try to make `make bench` more verbose, the description field will probably not be enough, we probably need to check the output of formatted code, or maybe a list of pass/failed checks but that still wouldn't fit in the description.
