### ISSUE TITLE
Store locations of metrics in the logs

### ISSUE THREAD

**Issue by art-w** [ocurrent/current-bench#286]
The `make bench` run can produce multiple json metrics incrementally in its output. In between two jsons, the user can interleave debug logs which are probably useful to understand a specific metric regression. When we parse the logs to discover the json metrics, we could remember their location: This would allow links in the UI to the specific lines in the log (with a url fragment `#L123` if the metric was produced at line 123). The current alternative is for the user to manually scroll through the log to find the lines of interest.

There are some issues when the same metric is produced at multiple points in the log... If that helps, we could link only to the first line and improve the UI later.

**Comment by punchagan** [comment]
Closed in #296. Being able to jump to the specific lines in the logs in the UI still depends on https://github.com/ocurrent/ocurrent/pull/309 being merged.
