### ISSUE TITLE
Make logs link more noticeable

### ISSUE THREAD

**Issue by gs0510** [ocurrent/current-bench#291]
From #285,

>Thanks I didn't notice this link, I think it could be made more noticeable (e.g. using the same style blue+underline for the link, and personally I think that the name of the build "110849-ocluster-build-87cd3f" only adds some "noise" and is not very useful for the end user, the link could just be named "execution logs").

Right now there;s ids in the logs that doesn't help the user figure out that the execution logs is indeed something useful. Perhaps we can add just a `Logs` link and hide the uuids?

**Comment by gs0510** [comment]
cc @art-w @punchagan What are your thoughts? :)

**Comment by punchagan** [comment]
Yes, that makes sense to me. The IDs are useful if we are trying to find the log on the server. But, I think we can get that out of the URL too.
