### ISSUE TITLE
Production logs and warnings

### ISSUE THREAD

**Issue by art-w** [ocurrent/current-bench#298]
In order to detect unexpected issues in production, it would be nice to have a high level logs of actions performed by the pipeline. Currently the logs are spread between the database, pipeline, and ocurrent logs, so it can be hard to spot the issue.

The other problem with this logs is social and organizational, as "who's looking at the log" is never super clear. It sounds a bit spammy, but I'm imagining slack/matrix messages to the current-bench team with all the steps performed in production ("Started benchmark for project XXX", "Got this json out", "Wrote to the database", "Set the github status to Passed", etc). I think it would be easier to flag and respond to issues that way without stepping on each other toes. We could also just report the failures rather than all the steps, but I'm hoping to catch silent issues earlier (for example https://github.com/ocurrent/current-bench/issues/297).

**Comment by gs0510** [comment]
This sounds great! Would we parse the logs for sending these individual messages? Or do you envision something else? :)

**Comment by punchagan** [comment]
Looks like we now have this with #327
