### ISSUE TITLE
Align the graphs vertically

### ISSUE THREAD

**Issue by art-w** [ocurrent/current-bench#315]
The UI shows the graphs in multiple columns. This makes it hard to read the regressions, because you have to visually jump horizontally and attempt to align the metric variations. See also https://github.com/ocurrent/current-bench/issues/247

It would probably work better if the graphs were full width, such that the vertical alignment is always correct. The height of the graphs could be smaller to not loose on information density.

See https://ziglang.org/perf/ for an example, where the x-axis is also using time and not just evenly spread commits (otherwise a big regression followed by a quick fix can be given too much importance in the timeline!)

**Comment by art-w** [comment]
Sure, the time as x-axis is only a suggestion! But it comes with its own challenges with the graph library ^^

**Comment by punchagan** [comment]
Closed in #320
