### ISSUE TITLE
Disabled worker / docker image

### ISSUE THREAD

**Issue by art-w** [ocurrent/current-bench#324]
Reported by @tmattio: When visiting the url of a PR from github ([example](https://autumn.ocamllabs.io/ocaml/dune/pull/5483)), the frontend autoselects the first "environment" (worker + docker image). But the list of environments also contains some disabled ones, so a recent PR will have no corresponding benchmarks to show. We should filter the environments list for each PR so that only the active ones are available.

**Comment by punchagan** [comment]
Yes, I was observing this myself with local testing yesterday, but didn't find the time to make an issue for this. This would be really nice to fix!
