### ISSUE TITLE
Hide closed PRs

### ISSUE THREAD

**Issue by art-w** [ocurrent/current-bench#346]
The old closed/merged PRs are always visible in the sidebar, which makes it harder to survey all the active benchmarks. These PRs also tend get stuck in a "running" state: https://autumn.ocamllabs.io/ocaml/dune/pull/5270?worker=autumn&image=ocaml%2Fopam%3Adebian-11-ocaml-4.13

**Comment by punchagan** [comment]
Hmm, they should actually get pushed to `Cancelled` state, if it is cancelled after the [cancel hooks have been setup](https://github.com/ocurrent/current-bench/blob/main/pipeline/lib/pipeline.ml#L44). Also, looks like this particular PR in question was closed about the same time when this change was [merged](https://github.com/ocurrent/current-bench/pull/231). So, it was probably not deployed?

Agree with hiding closed PRs to make it easier to navigate active benchmarks in the sidebar.
