### ISSUE TITLE
Allow bench.Dockerfile to exist outside the root

### ISSUE THREAD

**Issue by ElectreAAS** [ocurrent/current-bench#395]
Having a `bench.Dockerfile` at the root of the project isn't very clean, especially for big projects. It would be nice to unclutter this by allowing the file to be anywhere, or a specific other place..

**Comment by art-w** [comment]
A simple solution would be to list the custom dockerfile path/filename in the repo configuration(s), as we already do for the docker images, which would then also enable having multiple dockerfiles in different environments (as requested by @gridbugs )
