### ISSUE TITLE
Ability to run without previously cached image

### ISSUE THREAD

**Issue by 3Rafal** [ocurrent/current-bench#468]
While running merlin benchmarks, we use external tool [merl-an](https://github.com/pitag-ha/merl-an). It is installed as in here:
https://github.com/ocaml/merlin/pull/1640/files

When I add a changes to merl-an, the image is cached, so I have to change something in dockerfile in order to force it's build. Is there other way to do this?

**Comment by punchagan** [comment]
Currently, `current-bench` doesn't have a way to specify that the docker cache should be ignored for a particular benchmark run.

But, as a work around to rebuild the image when there are changes in the `merl-an` repository, you can use a hack like this, in your Dockerfile:

```dockerfile
ADD https://api.github.com/repos/pitag-ha/merl-an/git/refs/heads/main .merl-an-info
```

This would ensure that the layers starting from the clone of the repo are rebuilt, whenever the `merl-an` repo has changes.[We also use](https://github.com/ocurrent/current-bench/blob/main/pipeline/lib/custom_dockerfile.ml#L142-L148) this hack for supporting the feature where the benchmarks repository is different from the repository being benchmarked.

**Comment by 3Rafal** [comment]
Thanks @punchagan !
