### ISSUE TITLE
wrong commit links

### ISSUE THREAD

**Issue by samoht** [ocurrent/current-bench#53]
When clicking on a commit id in a graph, this points to a truncated url (which I think works fine because GH support this but would be nice to have the full hash).
But the main issue is that it always point to `https://github.com/mirage/index`, e.g. clicking on a commit ID on:

http://autumn.ocamllabs.io/mirage/irmin/pull/1312

leads to:

https://github.com/mirage/index/commit/49facfe

**Comment by rizo** [comment]
Thanks for reporting! Resolved in linked PR. I'll deploy this later today.
