### ISSUE TITLE
Add support for multi benchmarks in the UI

### ISSUE THREAD

**Issue by rizo** [ocurrent/current-bench#57]
We need to complete the frontend changes for #17.

This is my suggestion on what needs to be done:
* Fetch all available benchmarks with GraphQL in the UI.
* Add benchmarks menu to the sidebar.
* Request benchmark data for a specific benchmark.
* Add benchmark to the URI.

**Comment by rizo** [comment]
See this comment for a suggestion on the UI changes: https://github.com/ocurrent/current-bench/pull/20#issuecomment-754872568

**Comment by punchagan** [comment]
Is this issue still relevant? We already have a benchmarks menu, that shows up when there are multiple benchmarks. Not sure if there's more to be done here.

**Comment by gs0510** [comment]
Yes, it still is! We currently don't have any benchmarks that have "multiple names" but it'd be nice to support these! @punchagan we can talk more about this, if you have questions

**Comment by punchagan** [comment]
![image](https://user-images.githubusercontent.com/315678/146908748-061c1c5d-eedb-4de0-ba67-f539dfe85349.png)

We already show a benchmarks menu and the URI includes the benchmark name. Not sure, what more needs to be done, here @gs0510.

**Comment by gs0510** [comment]
Ah yes, sorry I think this can be closed now :)) Thanks @punchagan!
