### ISSUE TITLE
Improve precision in graphs

### ISSUE THREAD

**Issue by rizo** [ocurrent/current-bench#77]
Both the graphs and the metrics table currently have rounding issues as illustrated in the following graph:

<img width="434" alt="Screenshot 2021-03-30 at 17 40 26" src="https://user-images.githubusercontent.com/308413/113024755-04108e00-917f-11eb-87f2-1be56cba05c5.png">

**Comment by tatchi** [comment]
Should have been addressed in https://github.com/ocurrent/current-bench/pull/81
