### ISSUE TITLE
Detect when we try to access a PR that does not exist

### ISSUE THREAD

**Issue by tatchi** [ocurrent/current-bench#85]
There's a Javascript error and the whole page becomes blank when we try to access the benchmark results from a PR that does not exist. This can happen for instance when we manually modify the PR number in the URL.

We should handle that in a better way, like showing a message that tells the user that the PR does not exist (yet).

**Comment by gs0510** [comment]
Ah for this should we check the postgres DB for an entry and if it doesn't exist show error?

**Comment by rizo** [comment]
I think the issue was resolved with #86 (which is already deployed).

For instance, this PR does not exist: http://autumn.ocamllabs.io/mirage/index/pull/999 and we already show a "no data" message.
