### ISSUE TITLE
Benchmarks are not ordered correctly on the graphs

### ISSUE THREAD

**Issue by gs0510** [ocurrent/current-bench#9]
Currently, the benchmarks are sorted by the timestamp they were created at which doesn't always result in the correct graph. Sometimes the master & pull request commits are interspersed because the pipeline ran on the master more than once. One way to make it better would be to topologically sort the commits or display master benchmarks first followed by displaying the benchmarks of the commit in the PR.

**Comment by rizo** [comment]
Should be solved in the new UI.
