### ISSUE TITLE
Hasura Admin Secret

### ISSUE THREAD

**Issue by d4hines** [ocurrent/current-bench#92]
Hi 👋!
What is the best way to handle the `X-Hasura-Admin-Secret` value? It's currently hard-coded into the repo. Can this be used to do anything destructive? I'm not familiar with Hasura but it seems great, and I want to use Hasura Cloud for my own implementation of current-bench. I'll hard code into the client for now, but I don't want some jerk to DOS me if it can be easily avoided 😅

**Comment by gs0510** [comment]
Hi @d4hines! Thanks for pointing it out, I'm going to push a fix out in the next few minutes where you can put in an env file instead.

**Comment by tatchi** [comment]
> Hi @d4hines! Thanks for pointing it out, I'm going to push a fix out in the next few minutes where you can put in an env file instead. (and changing the key also)

I'm wondering if using an `.env` file would be useful here. The `secret` would still have to be sent over the wire right? Meaning that someone could inspect the header and grab it:

<img width="969" alt="Screenshot 2021-04-08 at 16 35 56" src="https://user-images.githubusercontent.com/5595092/114046820-72dd9d80-9889-11eb-998e-a99733104c0e.png">

I think also that these `.env` variables are statically replaced at build time, so one could also inspect the `js` file:

<img width="969" alt="Screenshot 2021-04-08 at 16 38 51" src="https://user-images.githubusercontent.com/5595092/114047127-bafcc000-9889-11eb-9919-e9899df389ce.png">

I'm definitely not a `Hasura` expert myself but I have seen in the doc that we can configure unauthenticated / public access: https://hasura.io/docs/latest/graphql/core/auth/authentication/unauthenticated-access.html#unauthenticated-access

Wouldn't that make more sense in our case?

**Comment by gs0510** [comment]
I think providing an  env file will help with users who want to setup current-bench locally, and in addition we can also setup Hasura to ensure that unauthenticated users can't do anything. Let me know what you think about that @tatchi

**Comment by tatchi** [comment]
> I think providing an env file will help with users who want to setup current-bench locally, and in addition we can also setup Hasura to ensure that unauthenticated users can't do anything. Let me know what you think about that @tatchi

What I was thinking about is to allow [unauthenticated requests](https://hasura.io/docs/latest/graphql/core/auth/authentication/unauthenticated-access.html#configuring-unauthenticated-public-access) so that the frontend doesn't have to provide any `admin (root)` secret.

**Comment by gs0510** [comment]
Fixed by #95
