### ISSUE TITLE
Hard-Coded URI's

### ISSUE THREAD

**Issue by d4hines** [ocurrent/current-bench#93]
There are several hard-coded URI's in the frontend and the pipeline. These should be moved to configuration, but for now they are easy enough to change in my own fork. However, there is another source of hard-coded URI's that I can't locate. My production pipeline (installed as a GH app) is failing. It's giving this warning:
```
current.github [WARNING] Set d4hines/marigold-tezos
                           refs/heads/master
                           902910d2/ocaml-benchmarks to
                           {"state":"failure","description":"Command \"docker\" \"run\" \"--security-opt\" \"seccomp=./aslr_seccomp.json\" \n\"--tmpfs\" \"/dev/shm:rw,noexec,nosuid,size=4g\" \"--rm\" \"-i\" \"sha256:98a","target_url":"http://autumn.ocamllabs.io/d4hines/marigold-tezos"} failed: 403 Forbidden
                           {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-commit-status"}
```

I can't track down where it's getting the URL http://autumn.ocamllabs.io/d4hines/marigold-tezos from. Any ideas?

**Comment by gs0510** [comment]
http://autumn.ocamllabs.io is the URL we display frontend on, are you running benchmarks for marigold-tezos? It should be coming from here: https://github.com/ocurrent/current-bench/blob/main/pipeline/lib/pipeline.ml#L62
